version: "3.9"

services:
  php:
    image: php:8.2-fpm
    container_name: whimsicalfrog-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    environment:
      # Tune FPM for a few workers in dev so requests don't serialize
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=8
      - PHP_FPM_PM_START_SERVERS=2
      - PHP_FPM_PM_MIN_SPARE_SERVERS=2
      - PHP_FPM_PM_MAX_SPARE_SERVERS=4
      # Ensure server-side vite helper points to nginx origin (which proxies to Vite)
      - WF_VITE_DEV=1
      - WF_VITE_ORIGIN=http://localhost:8080
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25-alpine
    container_name: whimsicalfrog-nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:cached
      # Use NGINX_CONF env var to select config. Default to dev proxy config.
      - ${NGINX_CONF:-./docker/nginx.dev.conf}:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# Usage:
#   docker compose up --build
#   Visit http://localhost:8080
# Notes:
# - Vite dev server can continue to run on your host at http://localhost:5176
# - All PHP pages & /api/* endpoints are served via nginx->php-fpm with multiple workers
