name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci || npm install
      - name: Lint
        run: npm run lint --if-present
      - name: Guards
        run: |
          npm run guard:templates:css --if-present
          npm run check:css:orphans --if-present
      - name: Build
        run: npm run build --if-present
      - name: PHP Lint
        run: |
          find . -type f -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l
