export const ADMIN_SECTION = {
    POS: 'pos',
    DASHBOARD: 'dashboard',
    INVENTORY: 'inventory',
    ORDERS: 'orders',
    CUSTOMERS: 'customers',
    CATEGORIES: 'categories',
    REPORTS: 'reports',
    MARKETING: 'marketing',
    SETTINGS: 'settings',
    BUSINESS_INFO: 'business-info',
    CSS_RULES: 'css-rules',
    ACTION_ICONS: 'action-icons',
    SHIPPING: 'shipping',
    SQUARE: 'square',
    COMMUNICATION: 'communication',
    DASHBOARD_CONFIG: 'dashboard-config',
    BACKGROUNDS: 'backgrounds',
    AREA_MAPPER: 'area-mapper',
    AI_SETTINGS: 'ai-settings',
    COST_BREAKDOWN: 'cost-breakdown',
    PRICE_SUGGESTIONS: 'price-suggestions',
    AUTOMATION: 'automation',
    INTENT_HEURISTICS: 'intent-heuristics',
    ITEM_ATTRIBUTES: 'item-attributes',
    BRAND_STYLING: 'brand-styling',
    NEWSLETTERS: 'newsletters',
    SOCIAL_MEDIA: 'social-media',
    THEME_WORDS: 'theme-words',
    MARKETING_SETTINGS: 'marketing-settings',
    RECEIPT_SETTINGS: 'receipt-settings',
    COUPONS: 'coupons',
    SECRETS: 'secrets',
    LOGS: 'logs',
    INVENTORY_ARCHIVE: 'inventory-archive',
    SITE_MAINTENANCE: 'site-maintenance',
    ADVANCED_TOOLS: 'advanced-tools',
    HELP_GUIDES: 'help-guides',
    SHOPPING_CART: 'shopping-cart',
    ROOM_MANAGER: 'room-manager',
    DB_STATUS: 'db-status',
    DB_QUERY_CONSOLE: 'db-query-console',
    INVENTORY_AUDIT: 'inventory-audit',
    CRON_MANAGER: 'cron-manager',
    SESSION_VIEWER: 'session-viewer',
    CART_SIMULATION: 'cart-simulation',
    SIZING_TOOLS: 'sizing-tools',
    MARKETING_CHECK: 'marketing-check',
    ADDRESS_CHECK: 'address-check',
    CSS_CATALOG: 'css-catalog',
    DB_MIGRATIONS_AUDIT: 'db-migrations-audit'
} as const;

export type AdminSection = typeof ADMIN_SECTION[keyof typeof ADMIN_SECTION];

export const SETTINGS_CATEGORY = {
    ECOMMERCE: 'ecommerce',
    SQUARE: 'square',
    AI: 'ai'
} as const;

export const SETTINGS_MODAL_SECTIONS = [
    ADMIN_SECTION.BUSINESS_INFO,
    ADMIN_SECTION.SHIPPING,
    ADMIN_SECTION.SQUARE,
    ADMIN_SECTION.COMMUNICATION,
    ADMIN_SECTION.DASHBOARD_CONFIG,
    ADMIN_SECTION.AREA_MAPPER,
    ADMIN_SECTION.AI_SETTINGS,
    ADMIN_SECTION.COST_BREAKDOWN,
    ADMIN_SECTION.PRICE_SUGGESTIONS,
    ADMIN_SECTION.AUTOMATION,
    ADMIN_SECTION.INTENT_HEURISTICS,
    ADMIN_SECTION.ITEM_ATTRIBUTES,
    ADMIN_SECTION.BRAND_STYLING,
    ADMIN_SECTION.NEWSLETTERS,
    ADMIN_SECTION.SOCIAL_MEDIA,
    ADMIN_SECTION.MARKETING_SETTINGS,
    ADMIN_SECTION.THEME_WORDS,
    ADMIN_SECTION.RECEIPT_SETTINGS,
    ADMIN_SECTION.COUPONS,
    ADMIN_SECTION.SECRETS,
    ADMIN_SECTION.LOGS,
    ADMIN_SECTION.INVENTORY_ARCHIVE,
    ADMIN_SECTION.SITE_MAINTENANCE,
    ADMIN_SECTION.ADVANCED_TOOLS,
    ADMIN_SECTION.SHOPPING_CART,
    ADMIN_SECTION.HELP_GUIDES,
    ADMIN_SECTION.ROOM_MANAGER,
] as const;
