<?php

declare(strict_types=1);

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/../includes/response.php';
require_once __DIR__ . '/../includes/auth_helper.php';

header('Content-Type: application/json; charset=utf-8');

const AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL = '(autogenerated)';
const AI_PROMPT_DROPDOWN_AUTOGENERATE_LEGACY_LABEL = '(autogenerate)';
const AI_PROMPT_DROPDOWN_DEFAULTS = [
    'room_name' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Holiday Collection',
        'Spring Garden Boutique',
        'Woodland Gift Nook',
        'Frog Atelier',
        'Cozy Candle Corner',
        'Artisan Market Hall',
    ],
    'door_label' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Holidays',
        'Seasonal',
        'Best Sellers',
        'New Arrivals',
        'Custom Gifts',
        'Featured',
    ],
    'room_description' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'A cozy holiday gift room with warm seasonal accents.',
        'A bright handcrafted market corner with open shelves.',
        'A whimsical frog-owned boutique for custom keepsakes.',
        'A playful studio featuring themed product staging zones.',
        'A calm premium display room with clean merchandising lines.',
    ],
    'scene_type' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'room',
        'house exterior',
        'house interior',
        'landing page',
        'shop page',
        'about page',
        'contact page',
        'info page',
        'modal',
        'dashboard page',
    ],
    'subject_species' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'no character (environment only)',
        'frog',
        'toad',
        'cat',
        'dog',
        'bird',
        'rabbit',
        'fox',
        'bear',
    ],
    'subject_headwear' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'no headwear',
        'fedora',
        'crafty hat',
        'beanie',
        'straw hat',
        'cowboy hat',
        'wizard hat',
        'sunhat',
    ],
    'room_theme' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'cozy cafe',
        'rustic farmhouse',
        'magical apothecary',
        'artisan bakery',
        'storybook gift shop',
        'modern boutique',
        'A cozy cabin settled in North Georgia mountains.',
    ],
    'display_furniture_style' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'tiered light-wood shelving units',
        'modern matte-black floating shelves',
        'rustic reclaimed wood display tables',
        'glass-front display cabinets',
        'industrial pipe-and-wood shelving',
        'curved boutique wall niches',
        'minimal white modular cubes',
        'vintage apothecary drawer wall',
    ],
    'thematic_accent_decorations' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'tiny potted succulents and miniature ceramic milk jugs',
        'small lanterns and mossy stones',
        'hanging ivy strands and brass trinkets',
        'vintage books and porcelain figurines',
        'woven baskets and dried florals',
        'mini chalkboards and painted pebbles',
        'glass bottles with fairy lights',
        'seasonal garlands and ribbon bundles',
    ],
    'frog_action' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'no characters present',
        'one subject casually reviewing the space layout',
        'two subjects relaxed in the scene foreground',
        'one mascot welcoming visitors with a friendly wave',
        'a proprietor adjusting display spacing with a tape measure',
        'the subject inspecting lighting over the shelving',
        'the subject reviewing a clipboard checklist',
        'the subject sweeping the floor with a small broom',
        'husband and wife frog chilling on the porch',
    ],
    'vibe_adjectives' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'refreshing and bright',
        'cozy and inviting',
        'playful and energetic',
        'calm and elegant',
        'warm and nostalgic',
        'whimsical and magical',
        'modern and premium',
        'rustic and handcrafted',
    ],
    'color_scheme' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        "robin's egg blue and soft orange",
        'sage green and cream',
        'dusty rose and antique gold',
        'navy and warm brass',
        'mint and coral',
        'charcoal and ivory',
        'lavender and pale teal',
        'terracotta and sand',
    ],
    'background_thematic_elements' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'giant floating fruit shapes',
        'oversized botanical motifs',
        'storybook clouds and stars',
        'subtle geometric wall inlays',
        'ornate vintage frames and arches',
        'floating paper lantern clusters',
        'soft mural waves and swirls',
        'woodland silhouettes and vines',
    ],
    'image_style_declaration' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'A high-quality render for room',
        'A photorealistic render for room',
        'A stylized illustration render for room',
        'A 3D cartoon render for room',
        'A painterly concept-art render for room',
    ],
    'location_phrase' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'inside a themed retail environment',
        'inside a cozy boutique interior',
        'inside a clean modern storefront',
        'inside a handcrafted market room',
        'at the front porch of a small cabin with yard crafts around',
        "inside the whimsical frog’s cottage",
        'front of the cabin with yard crafts all around',
    ],
    'character_statement' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'No characters are visible in this scene.',
        'Primary subject(s): {{frog_action}}.',
        'One proprietor is present and clearly visible: {{frog_action}}.',
        'Two partner characters are present and clearly visible: {{frog_action}}.',
        'A fedora-wearing frog proprietor is present: {{frog_action}}.',
        'Two frog partners are present; one in a fedora and one in a crafty hat: {{frog_action}}.',
    ],
    'aesthetic_statement' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        "Background walls/ceiling include decorative {{background_thematic_elements}} that reinforce the room's function.",
        'Walls and ceiling feature large-scale {{background_thematic_elements}} that strengthen the room story.',
        'Decorative {{background_thematic_elements}} frame the walls and ceiling to support the concept.',
        'The backdrops use prominent {{background_thematic_elements}} for visual identity.',
        'Background architecture incorporates thematic {{background_thematic_elements}} to anchor the scene.',
    ],
    'critical_constraint_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'CRITICAL CONSTRAINT: All display surfaces (shelves, racks, counters, tabletops, hooks, bins, stands) must remain completely empty and flat.',
        'CRITICAL CONSTRAINT: Keep every merchandising surface empty, unobstructed, and ready for future products.',
        'CRITICAL CONSTRAINT: No objects may occupy shelves, counters, racks, tabletops, hooks, bins, or stands.',
        'CRITICAL CONSTRAINT: Preserve clean, empty display planes across all merchandising fixtures.',
        'CRITICAL CONSTRAINT: All product-display fixtures must remain bare and flat for post-generation placement.',
    ],
    'no_props_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Do NOT place any props, decor, products, containers, signage, books, plants, objects, or accents on any display surface.',
        'Do NOT place decorative or functional objects on shelving, counters, tables, hooks, racks, bins, or stands.',
        'Do NOT add products, props, baskets, signage, florals, books, or accessories to display surfaces.',
        'Do NOT populate any merchandising surfaces with items of any kind.',
        'Do NOT stage objects on product-display fixtures; keep them completely clear.',
    ],
    'decorative_elements_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Keep decorative elements strictly on walls, ceiling, floor edges, corners, or perimeter zones away from display surfaces.',
        'Place decorative accents only on walls, ceiling, and perimeter floor zones, never on display fixtures.',
        'Constrain decorative details to architectural boundaries and wall/ceiling regions away from merchandising surfaces.',
        'Keep all aesthetic props to the perimeter and structural surfaces, not display planes.',
        'Position decor in edge zones and overhead areas only, leaving display fixtures untouched.',
    ],
    'open_display_zones_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Maintain large uninterrupted open display zones for future item placement.',
        'Preserve broad, unobstructed merchandising zones for future product insertion.',
        'Ensure generous open surface area remains available across all display fixtures.',
        'Leave continuous clear display space throughout the room for later catalog staging.',
        'Maintain clean and uninterrupted placement-ready zones on every display fixture.',
    ],
    'art_style_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Art style: neutral production concept render with clean composition.',
        'Art style: photorealistic architectural visualization.',
        'Art style: painterly concept art illustration.',
        "Art style: modern 3D children's cartoon animation (Pixar-like).",
        'Art style: stylized cel-shaded illustration.',
    ],
    'surfaces_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Surfaces: smooth, vibrant, saturated colors, clean presentation.',
        'Surfaces: clean materials, soft gloss, and vibrant but controlled color richness.',
        'Surfaces: polished, tidy, high-clarity textures with bright stylized color.',
        'Surfaces: simplified smooth geometry with crisp, appealing cartoon finish.',
        'Surfaces: refined, uncluttered, color-forward materials optimized for product staging.',
    ],
    'text_constraint_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Text constraint: strictly NO TEXT anywhere in the image.',
        'Text constraint: do not render letters, words, logos, labels, or signage text.',
        'Text constraint: avoid all typography and written marks in-scene.',
        'Text constraint: no textual elements of any kind may appear.',
        'Text constraint: output must be fully text-free.',
    ],
    'lighting_line' => [
        AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL,
        'Lighting: bright and inviting, highlighting empty display surface textures for product insertion.',
        'Lighting: clean boutique brightness that emphasizes open shelf and counter surfaces.',
        'Lighting: warm-balanced key and fill setup that keeps empty fixtures clearly visible.',
        'Lighting: vibrant retail-style illumination with clear separation on display planes.',
        'Lighting: welcoming high-clarity scene lighting optimized for future product compositing.',
    ],
];

function ai_prompt_templates_normalize_dropdown_values(array $rawOptions): array
{
    $seen = [];
    $normalized = [AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL];
    $values = [];

    foreach ($rawOptions as $raw) {
        $value = trim((string) $raw);
        if ($value === '') {
            continue;
        }
        if (strlen($value) > 191) {
            throw new InvalidArgumentException('Dropdown option values must be 191 characters or fewer');
        }
        $key = strtolower($value);
        if (
            isset($seen[$key])
            || $key === strtolower(AI_PROMPT_DROPDOWN_AUTOGENERATE_LABEL)
            || $key === AI_PROMPT_DROPDOWN_AUTOGENERATE_LEGACY_LABEL
        ) {
            continue;
        }
        $seen[$key] = true;
        $values[] = $value;
    }

    usort($values, static function (string $a, string $b): int {
        return strnatcasecmp($a, $b);
    });

    foreach ($values as $value) {
        $normalized[] = $value;
    }

    return $normalized;
}

function ai_prompt_templates_resolve_prompt_text(string $template, array $resolvedVariables): string
{
    $prompt = $template;
    for ($pass = 0; $pass < 5; $pass++) {
        $previous = $prompt;
        foreach ($resolvedVariables as $key => $value) {
            $prompt = str_replace('{{' . $key . '}}', (string) $value, $prompt);
        }
        if ($prompt === $previous) {
            break;
        }
    }
    return $prompt;
}

function ai_prompt_templates_init_tables(): void
{
    Database::execute("CREATE TABLE IF NOT EXISTS ai_prompt_templates (
        id INT AUTO_INCREMENT PRIMARY KEY,
        template_key VARCHAR(120) NOT NULL UNIQUE,
        template_name VARCHAR(180) NOT NULL,
        description TEXT NULL,
        context_type VARCHAR(80) NOT NULL DEFAULT 'generic',
        prompt_text LONGTEXT NOT NULL,
        is_active TINYINT(1) NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_context_active (context_type, is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

    Database::execute("CREATE TABLE IF NOT EXISTS ai_prompt_variables (
        id INT AUTO_INCREMENT PRIMARY KEY,
        variable_key VARCHAR(120) NOT NULL UNIQUE,
        display_name VARCHAR(180) NOT NULL,
        description TEXT NULL,
        sample_value VARCHAR(255) NULL,
        is_active TINYINT(1) NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

    Database::execute("CREATE TABLE IF NOT EXISTS ai_generation_history (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        template_key VARCHAR(120) NOT NULL,
        prompt_text LONGTEXT NOT NULL,
        variables_json LONGTEXT NULL,
        provider VARCHAR(80) NULL,
        model VARCHAR(180) NULL,
        status VARCHAR(40) NOT NULL DEFAULT 'queued',
        output_type VARCHAR(80) NULL,
        output_path VARCHAR(255) NULL,
        room_number VARCHAR(40) NULL,
        error_message TEXT NULL,
        created_by VARCHAR(120) NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_template_created (template_key, created_at),
        INDEX idx_status_created (status, created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

    Database::execute("CREATE TABLE IF NOT EXISTS ai_prompt_dropdown_options (
        id INT AUTO_INCREMENT PRIMARY KEY,
        variable_key VARCHAR(120) NOT NULL,
        option_value VARCHAR(191) NOT NULL,
        display_order INT NOT NULL DEFAULT 0,
        is_active TINYINT(1) NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY uniq_variable_option (variable_key, option_value),
        INDEX idx_variable_active_order (variable_key, is_active, display_order)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}

function ai_prompt_templates_seed_defaults(): void
{
    $defaultTemplate = <<<'PROMPT'
{{image_style_declaration}} {{room_number}}.
Room name: {{room_name}}.
Door label: {{door_label}}.
Display order: {{display_order}}.
Room description/context: {{room_description}}.

Create a themed {{scene_type}} with a {{room_theme}} direction {{location_phrase}}.

The area features prominent {{display_furniture_style}} intended for future product placement.
{{critical_constraint_line}}
{{no_props_line}}
{{decorative_elements_line}}
{{open_display_zones_line}}

{{character_statement}}

Atmosphere: {{vibe_adjectives}}.
Color palette: {{color_scheme}}.
{{aesthetic_statement}}

{{art_style_line}}
{{surfaces_line}}
{{text_constraint_line}}
{{lighting_line}}
PROMPT;

    $variables = [
        ['room_number', 'Room Number', 'Room identifier that the generated image belongs to.', '7'],
        ['room_name', 'Room Name', 'Human-friendly room name from the room setup form.', 'Holiday Collection'],
        ['door_label', 'Door Label', 'Short label displayed on the room door.', 'Holidays'],
        ['display_order', 'Display Order', 'Room order index in navigation.', '10'],
        ['room_description', 'Room Description', 'Freeform room description from room setup.', 'A cozy holiday gift room with warm seasonal accents.'],
        ['scene_type', 'Scene Type', 'Target page/container type (room, house, page, modal, etc.).', 'general page or environment'],
        ['subject_species', 'Subject Species', 'Primary subject species for character-driven scenes.', 'no character (environment only)'],
        ['subject_headwear', 'Subject Headwear', 'Headwear style for subject(s), if applicable.', 'no headwear'],
        ['room_theme', 'Room Theme / Business Type', 'General room purpose (cozy cafe, magical apothecary, artisan bakery).', 'cozy cafe'],
        ['display_furniture_style', 'Display Furniture Style', 'Type of empty display structures used in the room.', 'tiered light-wood shelving units'],
        ['thematic_accent_decorations', 'Thematic Accent Decorations', 'Small non-product separators/bookends placed intermittently.', 'tiny potted succulents and miniature ceramic milk jugs'],
        ['frog_action', 'Subject Action', 'Primary subject action for the scene. Keep as "no characters present" unless character options are selected.', 'no characters present'],
        ['vibe_adjectives', 'Vibe Adjectives', 'Atmosphere mood words.', 'refreshing and bright'],
        ['color_scheme', 'Color Scheme Combinations', 'Dominant color pairings for the scene.', "robin's egg blue and soft orange"],
        ['background_thematic_elements', 'Background Thematic Elements', 'Large decor elements on walls/ceiling to establish context.', 'giant floating fruit shapes'],
        ['image_style_declaration', 'Image Style Declaration', 'Lead-in phrase used before the room number.', 'A high-quality render for room'],
        ['location_phrase', 'Location', 'Location phrase used in the themed-scene sentence.', 'inside a themed retail environment'],
        ['character_statement', 'Character / Subject', 'Primary subject statement for the scene.', 'No characters should appear in this scene unless explicitly selected in subject options.'],
        ['aesthetic_statement', 'Aesthetic', 'Aesthetic statement describing background thematic elements.', "Background walls/ceiling include decorative {{background_thematic_elements}} that reinforce the room's function."],
        ['critical_constraint_line', 'Critical Constraint', 'Constraint line for keeping display surfaces empty.', 'CRITICAL CONSTRAINT: All display surfaces (shelves, racks, counters, tabletops, hooks, bins, stands) must remain completely empty and flat.'],
        ['no_props_line', 'No Props Line', 'Explicit ban on props and products on display surfaces.', 'Do NOT place any props, decor, products, containers, signage, books, plants, objects, or accents on any display surface.'],
        ['decorative_elements_line', 'Decorative Elements Line', 'Placement rule for decorative elements.', 'Keep decorative elements strictly on walls, ceiling, floor edges, corners, or perimeter zones away from display surfaces.'],
        ['open_display_zones_line', 'Open Display Zones Line', 'Rule to preserve large empty display zones.', 'Maintain large uninterrupted open display zones for future item placement.'],
        ['art_style_line', 'Art Style', 'Art-style declaration line.', 'Art style: use the selected style direction and keep it consistent across the full scene.'],
        ['surfaces_line', 'Surfaces', 'Surface treatment declaration line.', 'Surfaces: clear, well-defined materials with clean presentation and production-ready composition.'],
        ['text_constraint_line', 'Text Constraint', 'Constraint line prohibiting text in generated image.', 'Text constraint: strictly NO TEXT anywhere in the image.'],
        ['lighting_line', 'Lighting', 'Lighting declaration line.', 'Lighting: balanced and production-ready, keeping empty display surfaces clearly readable for later product insertion.'],
    ];

    $templateCountRow = Database::queryOne('SELECT COUNT(*) AS total FROM ai_prompt_templates');
    $variableCountRow = Database::queryOne('SELECT COUNT(*) AS total FROM ai_prompt_variables');
    $templateCount = (int) ($templateCountRow['total'] ?? 0);
    $variableCount = (int) ($variableCountRow['total'] ?? 0);

    // Seed core defaults only on first-run bootstrapping.
    // This avoids re-creating deleted templates and overwriting customized defaults on every request.
    if ($templateCount === 0 && $variableCount === 0) {
        foreach ($variables as $v) {
            Database::execute(
                "INSERT INTO ai_prompt_variables (variable_key, display_name, description, sample_value, is_active)
                 VALUES (?, ?, ?, ?, 1)
                 ON DUPLICATE KEY UPDATE
                    display_name = VALUES(display_name),
                    description = VALUES(description),
                    sample_value = VALUES(sample_value),
                    is_active = 1",
                [$v[0], $v[1], $v[2], $v[3]]
            );
        }

        Database::execute(
            "INSERT INTO ai_prompt_templates (template_key, template_name, description, context_type, prompt_text, is_active)
             VALUES (?, ?, ?, ?, ?, 1)
             ON DUPLICATE KEY UPDATE
                template_name = VALUES(template_name),
                description = VALUES(description),
                context_type = VALUES(context_type),
                prompt_text = VALUES(prompt_text),
                is_active = 1",
            [
                'room_staging_empty_shelves_v1',
                'Room Staging (Generic Baseline)',
                'Generic room/page/modal scene builder with optional subject and style controls.',
                'room_generation',
                $defaultTemplate
            ]
        );
    }

    // Remove legacy autogenerated variant so only the canonical label remains.
    Database::execute(
        "DELETE FROM ai_prompt_dropdown_options WHERE LOWER(option_value) = ?",
        [AI_PROMPT_DROPDOWN_AUTOGENERATE_LEGACY_LABEL]
    );

    foreach (AI_PROMPT_DROPDOWN_DEFAULTS as $variableKey => $values) {
        $normalizedValues = ai_prompt_templates_normalize_dropdown_values($values);
        $existingRows = Database::queryAll(
            'SELECT option_value FROM ai_prompt_dropdown_options WHERE variable_key = ?',
            [$variableKey]
        );

        $existingKeys = [];
        foreach ($existingRows as $row) {
            $value = trim((string) ($row['option_value'] ?? ''));
            if ($value === '') {
                continue;
            }
            $existingKeys[strtolower($value)] = true;
        }

        $maxOrderRow = Database::queryOne(
            'SELECT COALESCE(MAX(display_order), -1) AS max_order FROM ai_prompt_dropdown_options WHERE variable_key = ?',
            [$variableKey]
        );
        $nextDisplayOrder = ((int) ($maxOrderRow['max_order'] ?? -1)) + 1;

        foreach ($normalizedValues as $value) {
            $key = strtolower($value);
            if (isset($existingKeys[$key])) {
                continue;
            }

            Database::execute(
                "INSERT INTO ai_prompt_dropdown_options (variable_key, option_value, display_order, is_active)
                 VALUES (?, ?, ?, 1)",
                [$variableKey, $value, $nextDisplayOrder]
            );
            $existingKeys[$key] = true;
            $nextDisplayOrder++;
        }
    }

    // Ensure room_number/display_order never exist as dropdown option rows.
    Database::execute(
        "DELETE FROM ai_prompt_dropdown_options WHERE variable_key IN ('room_number', 'display_order')"
    );

}

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') {
    Response::json(['success' => true]);
}

$action = $_GET['action'] ?? $_POST['action'] ?? '';
if ($action === '' && ($_SERVER['REQUEST_METHOD'] ?? '') === 'GET') {
    $action = 'list_templates';
}

$readActions = ['list_templates', 'list_variables', 'list_history', 'list_dropdown_options'];
if (!in_array($action, $readActions, true)) {
    Response::validateMethod('POST');
}

AuthHelper::requireAdmin(403, 'Admin access required');

ai_prompt_templates_init_tables();
ai_prompt_templates_seed_defaults();

try {
    $input = json_decode(file_get_contents('php://input'), true) ?? [];

    switch ($action) {
        case 'list_templates': {
            $templates = Database::queryAll(
                'SELECT id, template_key, template_name, description, context_type, prompt_text, is_active, created_at, updated_at
                 FROM ai_prompt_templates
                 ORDER BY is_active DESC, template_name ASC'
            );
            Response::json(['success' => true, 'templates' => $templates]);
            break;
        }

        case 'list_variables': {
            $variables = Database::queryAll(
                'SELECT id, variable_key, display_name, description, sample_value, is_active, created_at, updated_at
                 FROM ai_prompt_variables
                 WHERE is_active = 1
                 ORDER BY display_name ASC'
            );
            Response::json(['success' => true, 'variables' => $variables]);
            break;
        }

        case 'list_dropdown_options': {
            $rows = Database::queryAll(
                'SELECT variable_key, option_value
                 FROM ai_prompt_dropdown_options
                 WHERE is_active = 1
                 ORDER BY variable_key ASC, display_order ASC, id ASC'
            );

            $optionsByVariable = [];
            foreach ($rows as $row) {
                $variableKey = trim((string) ($row['variable_key'] ?? ''));
                $value = trim((string) ($row['option_value'] ?? ''));
                if ($variableKey === '' || $value === '') {
                    continue;
                }
                if (!isset($optionsByVariable[$variableKey])) {
                    $optionsByVariable[$variableKey] = [];
                }
                $optionsByVariable[$variableKey][] = $value;
            }

            foreach ($optionsByVariable as $variableKey => $values) {
                $optionsByVariable[$variableKey] = ai_prompt_templates_normalize_dropdown_values($values);
            }

            Response::json(['success' => true, 'options_by_variable' => $optionsByVariable]);
            break;
        }

        case 'save_template': {
            $id = (int) ($input['id'] ?? 0);
            $templateKey = trim((string) ($input['template_key'] ?? ''));
            $templateName = trim((string) ($input['template_name'] ?? ''));
            $description = trim((string) ($input['description'] ?? ''));
            $contextType = trim((string) ($input['context_type'] ?? 'generic'));
            $promptText = trim((string) ($input['prompt_text'] ?? ''));
            $isActive = !empty($input['is_active']) ? 1 : 0;

            if ($templateKey === '' || $templateName === '' || $promptText === '') {
                Response::error('template_key, template_name, and prompt_text are required', null, 422);
            }

            if ($id > 0) {
                Database::execute(
                    'UPDATE ai_prompt_templates
                     SET template_key = ?, template_name = ?, description = ?, context_type = ?, prompt_text = ?, is_active = ?
                     WHERE id = ?',
                    [$templateKey, $templateName, $description, $contextType, $promptText, $isActive, $id]
                );
            } else {
                Database::execute(
                    'INSERT INTO ai_prompt_templates (template_key, template_name, description, context_type, prompt_text, is_active)
                     VALUES (?, ?, ?, ?, ?, ?)',
                    [$templateKey, $templateName, $description, $contextType, $promptText, $isActive]
                );
            }

            Response::json(['success' => true, 'message' => 'Template saved']);
            break;
        }

        case 'save_variables': {
            $incoming = $input['variables'] ?? null;
            if (!is_array($incoming)) {
                Response::error('variables array is required', null, 422);
            }

            foreach ($incoming as $row) {
                if (!is_array($row)) {
                    Response::error('Each variables entry must be an object', null, 422);
                }
                $variableKey = trim((string) ($row['variable_key'] ?? ''));
                $displayName = trim((string) ($row['display_name'] ?? ''));
                $description = trim((string) ($row['description'] ?? ''));
                $sampleValue = trim((string) ($row['sample_value'] ?? ''));
                $isActive = !array_key_exists('is_active', $row) || !empty($row['is_active']) ? 1 : 0;

                if ($variableKey === '' || !preg_match('/^[a-z0-9_]+$/', $variableKey)) {
                    Response::error('variable_key is required and must be snake_case', null, 422);
                }
                if ($displayName === '') {
                    Response::error('display_name is required for each variable', null, 422);
                }

                Database::execute(
                    'INSERT INTO ai_prompt_variables (variable_key, display_name, description, sample_value, is_active)
                     VALUES (?, ?, ?, ?, ?)
                     ON DUPLICATE KEY UPDATE
                        display_name = VALUES(display_name),
                        description = VALUES(description),
                        sample_value = VALUES(sample_value),
                        is_active = VALUES(is_active)',
                    [$variableKey, $displayName, $description, $sampleValue, $isActive]
                );
            }

            Response::json(['success' => true, 'message' => 'Variables saved']);
            break;
        }

        case 'delete_template': {
            $id = (int) ($input['id'] ?? 0);
            if ($id <= 0) {
                Response::error('Template id is required', null, 422);
            }

            $deleted = Database::execute('DELETE FROM ai_prompt_templates WHERE id = ?', [$id]);
            if ($deleted < 1) {
                Response::error('Template not found', null, 404);
            }
            Response::json(['success' => true, 'message' => 'Template deleted']);
            break;
        }

        case 'save_dropdown_options': {
            $incoming = $input['options_by_variable'] ?? null;
            if (!is_array($incoming)) {
                Response::error('options_by_variable object is required', null, 422);
            }

            foreach ($incoming as $variableKey => $options) {
                $key = trim((string) $variableKey);
                if ($key === '' || !preg_match('/^[a-z0-9_]+$/', $key)) {
                    Response::error('Invalid variable_key in options_by_variable', null, 422);
                }
                if ($key === 'room_number' || $key === 'display_order') {
                    Database::execute('DELETE FROM ai_prompt_dropdown_options WHERE variable_key = ?', [$key]);
                    continue;
                }
                if (!is_array($options)) {
                    Response::error('Each options_by_variable entry must be an array of strings', null, 422);
                }
                $normalizedValues = ai_prompt_templates_normalize_dropdown_values($options);
                Database::execute('DELETE FROM ai_prompt_dropdown_options WHERE variable_key = ?', [$key]);
                foreach ($normalizedValues as $index => $value) {
                    Database::execute(
                        'INSERT INTO ai_prompt_dropdown_options (variable_key, option_value, display_order, is_active) VALUES (?, ?, ?, 1)',
                        [$key, $value, $index]
                    );
                }
            }

            Response::json(['success' => true, 'message' => 'Dropdown options saved']);
            break;
        }

        case 'log_generation': {
            $templateKey = trim((string) ($input['template_key'] ?? ''));
            $promptText = trim((string) ($input['prompt_text'] ?? ''));
            $variablesJson = json_encode($input['variables'] ?? [], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $provider = trim((string) ($input['provider'] ?? ''));
            $model = trim((string) ($input['model'] ?? ''));
            $status = trim((string) ($input['status'] ?? 'queued'));
            $outputType = trim((string) ($input['output_type'] ?? 'room_background'));
            $outputPath = trim((string) ($input['output_path'] ?? ''));
            $roomNumber = trim((string) ($input['room_number'] ?? ''));
            $errorMessage = trim((string) ($input['error_message'] ?? ''));
            $createdBy = null;
            $user = AuthHelper::getCurrentUser();
            if (is_array($user)) {
                $createdBy = (string) ($user['user_id'] ?? $user['id'] ?? $user['username'] ?? '');
            }

            if ($templateKey === '' || $promptText === '') {
                Response::error('template_key and prompt_text are required', null, 422);
            }

            Database::execute(
                'INSERT INTO ai_generation_history (template_key, prompt_text, variables_json, provider, model, status, output_type, output_path, room_number, error_message, created_by)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                [$templateKey, $promptText, $variablesJson, $provider, $model, $status, $outputType, $outputPath, $roomNumber, $errorMessage, $createdBy]
            );

            Response::json(['success' => true, 'message' => 'Generation history saved']);
            break;
        }

        case 'build_room_prompt': {
            $templateKey = trim((string) ($input['template_key'] ?? ''));
            $roomNumber = trim((string) ($input['room_number'] ?? ''));
            $provider = trim((string) ($input['provider'] ?? ''));
            $model = trim((string) ($input['model'] ?? ''));
            $variables = is_array($input['variables'] ?? null) ? $input['variables'] : [];

            if ($templateKey === '') {
                Response::error('template_key is required', null, 422);
            }

            $template = Database::queryOne(
                'SELECT template_key, prompt_text FROM ai_prompt_templates WHERE template_key = ? LIMIT 1',
                [$templateKey]
            );
            if (!$template) {
                Response::error('Template not found', null, 404);
            }

            $defaults = [];
            $rows = Database::queryAll('SELECT variable_key, sample_value FROM ai_prompt_variables WHERE is_active = 1');
            foreach ($rows as $row) {
                $key = (string) ($row['variable_key'] ?? '');
                if ($key !== '') {
                    $defaults[$key] = (string) ($row['sample_value'] ?? '');
                }
            }

            $resolved = $defaults;
            foreach ($variables as $k => $v) {
                $resolved[(string) $k] = trim((string) $v);
            }

            $prompt = ai_prompt_templates_resolve_prompt_text((string) ($template['prompt_text'] ?? ''), $resolved);

            $user = AuthHelper::getCurrentUser();
            $createdBy = null;
            if (is_array($user)) {
                $createdBy = (string) ($user['user_id'] ?? $user['id'] ?? $user['username'] ?? '');
            }

            Database::execute(
                'INSERT INTO ai_generation_history (template_key, prompt_text, variables_json, provider, model, status, output_type, room_number, created_by)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
                [$templateKey, $prompt, json_encode($resolved, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), $provider, $model, 'prompt_built', 'room_background_prompt', $roomNumber, $createdBy]
            );

            Response::json([
                'success' => true,
                'template_key' => $templateKey,
                'prompt_text' => $prompt,
                'resolved_variables' => $resolved,
                'message' => 'Room prompt built and logged'
            ]);
            break;
        }

        case 'list_history': {
            $history = Database::queryAll(
                'SELECT id, template_key, provider, model, status, output_type, output_path, room_number, error_message, created_by, created_at
                 FROM ai_generation_history
                 ORDER BY id DESC
                 LIMIT 100'
            );
            Response::json(['success' => true, 'history' => $history]);
            break;
        }

        default:
            Response::error('Invalid action', null, 400);
    }
} catch (Throwable $e) {
    Response::error($e->getMessage(), null, 500);
}
