name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Quarantine duplicate/backup files (CI enforcement)
        run: |
          chmod +x scripts/maintenance/quarantine_duplicates.sh || true
          scripts/maintenance/quarantine_duplicates.sh || true
          if ! git diff --quiet; then
            echo "::error ::Quarantine moved duplicate/backup files. Commit these changes locally before pushing."
            git status --porcelain
            exit 1
          fi

      - name: Sweep '-old' pattern files (CI enforcement)
        run: |
          chmod +x scripts/maintenance/sweep_old_files.sh || true
          scripts/maintenance/sweep_old_files.sh || true
          if ! git diff --quiet; then
            echo "::error ::Sweep moved '-old' pattern files. Commit these changes locally before pushing."
            echo "\n=== Diff (name-status) ==="
            git --no-pager diff --name-status
            echo "\n=== Diff (stat) ==="
            git --no-pager diff --stat
            echo "\n=== Status (porcelain) ==="
            git status --porcelain
            exit 1
          fi

      - name: Run style guard (no inline styles)
        run: npm run guard:styles

      - name: Run brand color and font guards
        run: npm run guard:brand-and-fonts

      - name: Run z-index guard
        run: npm run guard:z-index

      - name: Run no-raw-fetch guard (enforce ApiClient usage)
        run: npm run guard:fetch

      - name: Smoke test API client usage
        run: npm run smoke:api-client

      - name: Fail on stray backup files outside backups/
        run: |
          set -e
          echo "Checking for stray backups outside backups/ ..."
          # Find *.bak, *.backup, *.backup.* and files with a trailing numeric suffix like "name 2.ext"
          offenders=$(find . -path './backups' -prune -o -type f \
            \( -name '*.bak' -o -name '*.backup' -o -name '*.backup.*' -o -regex '.* [0-9]+\..*' \) -print)
          if [ -n "$offenders" ]; then
            echo "Found backup-like files outside backups/:"
            echo "$offenders"
            echo "::error ::Stray backup files detected outside backups/"
            exit 1
          fi

      - name: Fail on "-old" pattern files outside backups/ (CI mirror)
        run: |
          set -e
          echo "Checking for '-old' pattern files outside backups/ ..."
          offenders=$(git ls-files | grep -Ei '(^|/)([^/]*(-old|_old|\.old)[^/]*)$' | grep -Ev '^backups/' || true)
          if [ -n "$offenders" ]; then
            echo "Found '-old' pattern files outside backups/:"
            echo "$offenders"
            echo "::error ::'-old' pattern files must be stored under backups/"
            exit 1
          fi

      - name: Lint JS
        run: npm run lint

      - name: Lint CSS
        run: npm run lint:css

      - name: Check orphaned CSS
        run: npm run check:css:orphans
