name: Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to deploy (branch or tag)"
        required: false
        default: "main"
  push:
    branches:
      - main
    paths-ignore:
      - 'documentation/**'
      - '*.md'
      - '**/*.md'

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  SSH_ALIAS: github.com-whf
  REPO: r0ckitj0n/whimsicalfrog

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://whimsicalfrog.us/
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout (read-only)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ github.event.inputs.ref || github.ref }}
          fetch-depth: 1

      - name: Setup SSH alias (least-privilege key)
        uses: ./.github/actions/setup-ssh-alias
        with:
          ssh-private-key: ${{ secrets.WHF_DEPLOY_KEY }}
          ssh-alias: ${{ env.SSH_ALIAS }}
          ssh-host: github.com
          ssh-key-path: ~/.ssh/whf_deploy_key

      - name: Verify repo access via alias (ls-remote)
        run: |
          set -euo pipefail
          git ls-remote git@${{ env.SSH_ALIAS }}:${{ env.REPO }} HEAD | tee /tmp/lsremote.txt
          test -s /tmp/lsremote.txt

      - name: Build (placeholder)
        run: |
          set -euo pipefail
          npm ci
          npm run build --if-present

      - name: Deploy (placeholder)
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          set -euo pipefail
          echo "Ready to deploy to $DEPLOY_HOST as $DEPLOY_USER into $DEPLOY_PATH"
          # Example rsync or ssh deploy commands would go here, using additional secrets as needed.
          # rsync -az --delete dist/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
