name: Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to deploy (branch or tag)"
        required: false
        default: "main"
  push:
    branches:
      - main
    paths-ignore:
      - 'documentation/**'
      - '*.md'
      - '**/*.md'

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  SSH_ALIAS: github.com-whf
  REPO: r0ckitj0n/whimsicalfrog

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://whimsicalfrog.us/
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout (read-only)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ github.event.inputs.ref || github.ref }}
          fetch-depth: 1

      - name: Setup SSH alias (least-privilege key)
        uses: ./.github/actions/setup-ssh-alias
        with:
          ssh-private-key: ${{ secrets.WHF_DEPLOY_KEY }}
          ssh-alias: ${{ env.SSH_ALIAS }}
          ssh-host: github.com
          ssh-key-path: ~/.ssh/whf_deploy_key

      - name: Verify repo access via alias (ls-remote)
        run: |
          set -euo pipefail
          git ls-remote git@${{ env.SSH_ALIAS }}:${{ env.REPO }} HEAD | tee /tmp/lsremote.txt
          test -s /tmp/lsremote.txt

      - name: Build (placeholder)
        run: |
          set -euo pipefail
          npm ci
          npm run build --if-present

      - name: Setup SSH for deploy host
        shell: bash
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          WHF_DEPLOY_KEY: ${{ secrets.WHF_DEPLOY_KEY }}
        run: |
          set -euo pipefail
          : "${DEPLOY_HOST:?Missing DEPLOY_HOST secret}"
          mkdir -p ~/.ssh
          # Prefer a dedicated DEPLOY_SSH_KEY if provided, else reuse WHF_DEPLOY_KEY
          if [ -n "${DEPLOY_SSH_KEY:-}" ]; then
            echo "$DEPLOY_SSH_KEY" > ~/.ssh/deploy_key
          else
            if [ -z "${WHF_DEPLOY_KEY:-}" ]; then
              echo "::error::No DEPLOY_SSH_KEY or WHF_DEPLOY_KEY provided for deploy auth" >&2
              exit 1
            fi
            echo "$WHF_DEPLOY_KEY" > ~/.ssh/deploy_key
          fi
          chmod 600 ~/.ssh/deploy_key
          # Add deploy host to known_hosts
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy (rsync over SSH)
        shell: bash
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          set -euo pipefail
          : "${DEPLOY_USER:?Missing DEPLOY_USER}"
          : "${DEPLOY_PATH:?Missing DEPLOY_PATH}"
          test -d dist || { echo "::error::dist/ not found; ensure build step produced artifacts" >&2; exit 1; }
          RSYNC_RSH='ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes'
          rsync -az --delete -e "$RSYNC_RSH" dist/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/dist/"
