name: PHP Lint and DB Smoke

on:
  pull_request:
  push:
    branches: [ main, master, develop, "feature/**" ]

jobs:
  php-lint:
    name: PHP Syntax Lint (changed files)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Detect changed PHP files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.php

      - name: List changed files
        run: |
          echo "Changed PHP files:" 
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do echo "- $file"; done

      - name: Run php -l on changed files (or all if none detected)
        shell: bash
        run: |
          set -euo pipefail
          files=( ${{ steps.changed-files.outputs.all_changed_files }} )
          if [ ${#files[@]} -eq 0 ]; then
            echo "No changed PHP files detected; linting all PHP files to be safe."
            mapfile -t files < <(git ls-files '*.php')
          fi
          fail=0
          for f in "${files[@]}"; do
            if [ -f "$f" ]; then
              php -l "$f" || fail=1
            fi
          done
          exit $fail

  db-smoke:
    name: Optional DB Smoke Test
    if: ${{ vars.WF_ENABLE_DB_SMOKE == 'true' }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: whimsicalfrog
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -prootpass --silent; then
              echo "MySQL is ready"; break; fi; echo "Waiting for MySQL..."; sleep 2; done

      - name: Run API smoke test against disposable MySQL
        env:
          WF_DEBUG_SMOKE: '1'
        run: |
          set -e
          php -r "\
            parse_str('target=live&host=127.0.0.1&db=whimsicalfrog&user=root&pass=rootpass&port=3306', $_GET); \
            chdir(getcwd()); \
            include 'api/db_smoke_test.php'; \
          "
